### PR TITLE
Remove old secret from env samples

### PR DESCRIPTION
**Pull request by imcgonigle**
This PR remove a secret that shouldn't have been committed... The old secret has been deleted

### CODE REVIEW

**Review by FonzMP — APPROVED** [review]
LGTM :shipit:

**Review by gileswells — DISMISSED** [review]
This should be fixed with a forced push that rewrites the git history. It'll mess with any active PRs so if we can wait till after Alex finishes his thing that would likely be a very good thing for him. In the end this is a publc repo so this is out there already and archived most likely.

https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository

**Comment by FonzMP** [comment]
> This should be fixed with a forced push that rewrites the git history. It'll mess with any active PRs so if we can wait till after Alex finishes his thing that would likely be a very good thing for him. In the end this is a publc repo so this is out there already and archived most likely.
> 
> https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository

@gileswells FYSA - I believe he went in and changed the app secret prior to this PR, so I'm not sure we'll need the above. If we're concerned with removing the previous value I could see this, but I think we're good with just removing the old secret from the sample cause it's no longer in a functional state.

**Comment by gileswells** [comment]
I feel like the history rewrite is the better solution despite it being inactive. That being said, with it being inactive this method is acceptable.

**Pull request merged**
