### PR TITLE
[API-28463] - Remove Fortify/WASA header from MR template

### PR DESCRIPTION
**Pull request by gileswells**
Triggered by https://github.com/department-of-veterans-affairs/lighthouse-devops-support/pull/2897

https://jira.devops.va.gov/browse/API-28463

### CODE REVIEW

**Review by Cgfor3 — APPROVED** [review]
👍

**Comment by jw81** [comment]
Since we had to replace the old CodeQL config with a new CodeQL config, I _think_ the old CodeQL tasks on this PR are gonna wait for eternity.  So we may have to hit that "Merge without waiting for requirements to be met" checkbox when it's time to merge this in.  (or just create a new PR and throw this change in there)

**Comment by gileswells** [comment]
Hoping closing will reset checks

**Comment by gileswells** [comment]
Didn't work. Making a new PR

**Pull request closed without merging**
