### PR TITLE
[API-21947] - Remove auth requirement on release notes endpoint

### PR DESCRIPTION
**Pull request by gileswells**
https://vajira.max.gov/browse/API-21947

This endpoint holds no protected data and doesn't appear to _NEED_ any token to access as all the data held in this endpoint is also accessible through the legacy.json file public portal already consumes off network.

### CODE REVIEW

**Review by imcgonigle — DISMISSED** [review]
Looks good to me as long as everyone else is fine making it public.

**Review by jw81 — APPROVED** [review]

**Review by jw81 — APPROVED** [review]

**Comment by zaslow** [comment]
@jw81 @gileswells Is there any update on when you are planning to merge + deploy this change?

**Comment by gileswells** [comment]
@zaslow Sorry, missed your comment. Had to hold for code freeze but it'll go out in the next day.

**Comment by zaslow** [comment]
@gileswells All good, thanks for the update!

**Pull request merged**
